# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from introduction import introui
from stats import statui
from prevention import preui
from ransomware import ranui
from course import courseui
import sys

def mainui(abc):
    f0 = QtWidgets.QFrame(abc)
    f0.setGeometry(QtCore.QRect(0, 0, 801, 551))
    f0.setStyleSheet("background-color: rgb(255, 255, 255);")
    f0.setFrameShape(QtWidgets.QFrame.StyledPanel)
    f0.setFrameShadow(QtWidgets.QFrame.Raised)
    f0.setObjectName("f0")
    title = QtWidgets.QLabel(f0)
    title.setGeometry(QtCore.QRect(0, 0, 801, 271))
    title.setFrameShape(QtWidgets.QFrame.Panel)
    title.setText("")
    title.setPixmap(QtGui.QPixmap("title.jpg"))
    title.setObjectName("title")
    f1 = QtWidgets.QFrame(f0)
    f1.setGeometry(QtCore.QRect(0, 280, 801, 271))
    f1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
    f1.setStyleSheet("")
    f1.setFrameShape(QtWidgets.QFrame.StyledPanel)
    f1.setFrameShadow(QtWidgets.QFrame.Raised)
    f1.setObjectName("f1")
    introduction = QtWidgets.QPushButton(f1)
    introduction.setGeometry(QtCore.QRect(20, 20, 131, 31))
    font = QtGui.QFont()
    font.setFamily("Rockwell")
    font.setPointSize(11)
    font.setBold(True)
    font.setWeight(75)
    introduction.setFont(font)
    introduction.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    introduction.setStyleSheet("background-color: rgb(60, 241, 81)")
    introduction.setInputMethodHints(QtCore.Qt.ImhNone)
    introduction.setObjectName("introduction")
    statistics = QtWidgets.QPushButton(f1)
    statistics.setGeometry(QtCore.QRect(20, 60, 131, 31))
    font = QtGui.QFont()
    font.setFamily("Rockwell")
    font.setPointSize(11)
    font.setBold(True)
    font.setWeight(75)
    statistics.setFont(font)
    statistics.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    statistics.setStyleSheet("background-color: rgb(60, 241, 81)")
    statistics.setObjectName("statistics")
    ransomware = QtWidgets.QPushButton(f1)
    ransomware.setGeometry(QtCore.QRect(20, 100, 131, 31))
    font = QtGui.QFont()
    font.setFamily("Rockwell")
    font.setPointSize(11)
    font.setBold(True)
    font.setWeight(75)
    ransomware.setFont(font)
    ransomware.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    ransomware.setStyleSheet("background-color: rgb(60, 241, 81)")
    ransomware.setObjectName("ransomware")
    prevension = QtWidgets.QPushButton(f1)
    prevension.setGeometry(QtCore.QRect(20, 140, 131, 31))
    font = QtGui.QFont()
    font.setFamily("Rockwell")
    font.setPointSize(11)
    font.setBold(True)
    font.setWeight(75)
    prevension.setFont(font)
    prevension.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    prevension.setStyleSheet("background-color: rgb(60, 241, 81)")
    prevension.setObjectName("prevension")
    courses = QtWidgets.QPushButton(f1)
    courses.setGeometry(QtCore.QRect(20, 180, 131, 31))
    font = QtGui.QFont()
    font.setFamily("Rockwell")
    font.setPointSize(11)
    font.setBold(True)
    font.setWeight(75)
    courses.setFont(font)
    courses.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    courses.setStyleSheet("background-color: rgb(60, 241, 81)")
    courses.setObjectName("courses")
    cyber = QtWidgets.QLabel(f1)
    cyber.setGeometry(QtCore.QRect(210, 20, 371, 51))
    font = QtGui.QFont()
    font.setFamily("Arial Black")
    font.setPointSize(18)
    font.setBold(True)
    font.setItalic(True)
    font.setWeight(75)
    cyber.setFont(font)
    cyber.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(52, 203, 70, 255), stop:1 rgba(255, 255, 255, 255));")
    cyber.setObjectName("cyber")
    cyber_def = QtWidgets.QLabel(f1)
    cyber_def.setGeometry(QtCore.QRect(250, 80, 531, 100))
    font = QtGui.QFont()
    font.setFamily("Arial")
    font.setPointSize(12)
    font.setBold(True)
    font.setWeight(75)
    cyber_def.setFont(font)
    cyber_def.setOpenExternalLinks(False)
    cyber_def.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    cyber_def.setObjectName("cyber_def")

    exitb = QtWidgets.QPushButton(f1)
    exitb.setGeometry(QtCore.QRect(20,220,131,31))
    font = QtGui.QFont()
    font.setFamily("Rockwell")
    font.setPointSize(11)
    font.setBold(True)
    font.setWeight(75)
    exitb.setFont(font)
    exitb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    exitb.setStyleSheet("background-color: rgb(60, 241, 81)")
    exitb.setInputMethodHints(QtCore.Qt.ImhNone)
    exitb.setObjectName("exitb")

    introduction.setText( "Introduction")
    statistics.setText( "Statistics")
    ransomware.setText( "Ransomware")
    prevension.setText( "Prevention")
    courses.setText( "Courses")
    cyber.setText( " Cyber Crime :")
    exitb.setText("Exit")
    cyber_def.setText( "Cybercrimes can be defined as: Offences that are committed \n""against individuals or groups of individuals with a criminal motive to\n" "intentionally harm the reputation of the victim or cause physical or\n""mental harm,or loss, to the victim directly or indirectly, using modern\n" "telecommunication networks")

    f0.show()
    f1.show()
    introduction.show()
    statistics.show()
    prevension.show()
    courses.show()
    cyber.show()
    exitb.show()
    cyber_def.show()
    
    def fuct():
        f0.hide()
        f1.hide()
        title.hide()
        introduction.hide()
        statistics.hide()
        ransomware.hide()
        prevension.hide()
        courses.hide()
        cyber.hide()
        cyber_def.hide()
        introui(abc)
        
    introduction.clicked.connect(fuct)

    def fuct1():
        f0.hide()
        f1.hide()
        title.hide()
        introduction.hide()
        statistics.hide()
        ransomware.hide()
        prevension.hide()
        courses.hide()
        cyber.hide()
        cyber_def.hide()
        statui(abc)

    statistics.clicked.connect(fuct1)

    def fuct2():
        f0.hide()
        f1.hide()
        title.hide()
        introduction.hide()
        statistics.hide()
        ransomware.hide()
        prevension.hide()
        courses.hide()
        cyber.hide()
        cyber_def.hide()
        ranui(abc)

    ransomware.clicked.connect(fuct2)
    

    def fuct3():
        f0.hide()
        f1.hide()
        title.hide()
        introduction.hide()
        statistics.hide()
        ransomware.hide()
        prevension.hide()
        courses.hide()
        cyber.hide()
        cyber_def.hide()
        preui(abc)

    prevension.clicked.connect(fuct3)

    def fuct4():
        f0.hide()
        f1.hide()
        title.hide()
        introduction.hide()
        statistics.hide()
        ransomware.hide()
        prevension.hide()
        courses.hide()
        cyber.hide()
        cyber_def.hide()
        courseui(abc)

    courses.clicked.connect(fuct4)

    def exit1():
        sys.exit()

    exitb.clicked.connect(exit1)
