# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'course.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import main

def courseui(abc):
    f2 = QtWidgets.QFrame(abc)
    f2.setGeometry(QtCore.QRect(0, 0, 801, 551))
    f2.setStyleSheet("background-color: rgb(255, 255, 255);")
    f2.setFrameShape(QtWidgets.QFrame.StyledPanel)
    f2.setFrameShadow(QtWidgets.QFrame.Sunken)
    f2.setLineWidth(0)
    f2.setObjectName("f2")
    course_head = QtWidgets.QLabel(f2)
    course_head.setGeometry(QtCore.QRect(140, 10, 401, 31))
    font = QtGui.QFont()
    font.setFamily("Rockwell Condensed")
    font.setPointSize(16)
    font.setBold(True)
    font.setItalic(True)
    font.setUnderline(False)
    font.setWeight(75)
    course_head.setFont(font)
    course_head.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(142, 192, 52, 255), stop:1 rgba(255, 255, 255, 255));")
    course_head.setFrameShape(QtWidgets.QFrame.Panel)
    course_head.setFrameShadow(QtWidgets.QFrame.Sunken)
    course_head.setObjectName("course_head")
    edx = QtWidgets.QLabel(f2)
    edx.setGeometry(QtCore.QRect(20, 50, 111, 31))
    font = QtGui.QFont()
    font.setFamily("Cooper Black")
    font.setPointSize(12)
    font.setItalic(True)
    font.setUnderline(True)
    edx.setFont(font)
    edx.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(142, 192, 52, 255), stop:1 rgba(255, 255, 255, 255));")
    edx.setObjectName("edx")
    l0 = QtWidgets.QLabel(f2)
    l0.setGeometry(QtCore.QRect(20, 90, 261, 16))
    font = QtGui.QFont()
    font.setPointSize(10)
    font.setBold(True)
    font.setUnderline(True)
    font.setWeight(75)
    l0.setFont(font)
    l0.setObjectName("l0")
    l1 = QtWidgets.QLabel(f2)
    l1.setGeometry(QtCore.QRect(50, 110, 611, 16))
    font = QtGui.QFont()
    font.setPointSize(10)
    l1.setFont(font)
    l1.setOpenExternalLinks(True)
    l1.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    l1.setObjectName("l1")
    l2 = QtWidgets.QLabel(f2)
    l2.setGeometry(QtCore.QRect(20, 140, 251, 16))
    font = QtGui.QFont()
    font.setPointSize(10)
    font.setBold(True)
    font.setItalic(False)
    font.setUnderline(True)
    font.setWeight(75)
    l2.setFont(font)
    l2.setObjectName("l2")
    l3 = QtWidgets.QLabel(f2)
    l3.setGeometry(QtCore.QRect(50, 160, 481, 16))
    font = QtGui.QFont()
    font.setPointSize(10)
    l3.setFont(font)
    l3.setOpenExternalLinks(True)
    l3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    l3.setObjectName("l3")
    l4 = QtWidgets.QLabel(f2)
    l4.setGeometry(QtCore.QRect(20, 190, 211, 16))
    font = QtGui.QFont()
    font.setPointSize(10)
    font.setBold(True)
    font.setUnderline(True)
    font.setWeight(75)
    l4.setFont(font)
    l4.setObjectName("l4")
    l5 = QtWidgets.QLabel(f2)
    l5.setGeometry(QtCore.QRect(50, 210, 441, 16))
    font = QtGui.QFont()
    font.setPointSize(10)
    l5.setFont(font)
    l5.setOpenExternalLinks(True)
    l5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    l5.setObjectName("l5")
    coursera = QtWidgets.QLabel(f2)
    coursera.setGeometry(QtCore.QRect(20, 260, 251, 41))
    font = QtGui.QFont()
    font.setFamily("Cooper Black")
    font.setPointSize(12)
    font.setBold(False)
    font.setItalic(True)
    font.setUnderline(True)
    font.setWeight(50)
    coursera.setFont(font)
    coursera.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(142, 192, 52, 255), stop:1 rgba(255, 255, 255, 255));")
    coursera.setObjectName("coursera")
    l6 = QtWidgets.QLabel(f2)
    l6.setGeometry(QtCore.QRect(20, 320, 251, 16))
    font = QtGui.QFont()
    font.setPointSize(10)
    font.setBold(True)
    font.setUnderline(True)
    font.setWeight(75)
    l6.setFont(font)
    l6.setObjectName("l6")
    l7 = QtWidgets.QLabel(f2)
    l7.setGeometry(QtCore.QRect(60, 340, 371, 16))
    font = QtGui.QFont()
    font.setPointSize(10)
    l7.setFont(font)
    l7.setOpenExternalLinks(True)
    l7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    l7.setObjectName("l7")
    l8 = QtWidgets.QLabel(f2)
    l8.setGeometry(QtCore.QRect(20, 370, 271, 16))
    font = QtGui.QFont()
    font.setPointSize(10)
    font.setBold(True)
    font.setUnderline(True)
    font.setWeight(75)
    l8.setFont(font)
    l8.setObjectName("l8")
    l9 = QtWidgets.QLabel(f2)
    l9.setGeometry(QtCore.QRect(60, 390, 441, 16))
    font = QtGui.QFont()
    font.setPointSize(10)
    l9.setFont(font)
    l9.setOpenExternalLinks(True)
    l9.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    l9.setObjectName("l9")
    l10 = QtWidgets.QLabel(f2)
    l10.setGeometry(QtCore.QRect(20, 420, 261, 16))
    font = QtGui.QFont()
    font.setPointSize(10)
    font.setBold(True)
    font.setUnderline(True)
    font.setWeight(75)
    l10.setFont(font)
    l10.setObjectName("l10")
    l11 = QtWidgets.QLabel(f2)
    l11.setGeometry(QtCore.QRect(60, 440, 431, 16))
    font = QtGui.QFont()
    font.setPointSize(10)
    l11.setFont(font)
    l11.setOpenExternalLinks(True)
    l11.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
    l11.setObjectName("l11")
    back = QtWidgets.QPushButton(f2)
    back.setGeometry(QtCore.QRect(20, 10, 71, 31))
    font = QtGui.QFont()
    font.setFamily("Rockwell")
    font.setPointSize(9)
    font.setBold(True)
    font.setWeight(75)
    back.setFont(font)
    back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    back.setStyleSheet("")
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap("back1600.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    back.setIcon(icon)
    back.setObjectName("back")

    course_head.setText("   Online Courses for Cyber Security")
    edx.setText("Website: EDX")
    l0.setText("1.Name:Introduction to CyberSecurity")
    l1.setText("Link: https://www.edx.org/course/introduction-cybersecurity-uwashingtonx-cyb001x")
    l2.setText("2.Name:CyberSecurity Fundamentals")
    l3.setText("Link: https://www.edx.org/course/cybersecurity-fundamentals-ritx-cyber501x-2")
    l4.setText("3.Name:Network Security")
    l5.setText(" Link: https://www.edx.org/course/network-security-ritx-cyber504x")
    coursera.setText("Website:COURSERA")
    l6.setText("1.Name:Detecting cyber Attacks")
    l7.setText("Link: https://www.coursera.org/learn/detecting-cyber-attacks")
    l8.setText("2.Name: CyberSecurity Fundamentals ")
    l9.setText("Link: https://www.coursera.org/specializations/cyber-security")
    l10.setText("3.CyberSecurity for Bussiness")
    l11.setText("Link: https://www.coursera.org/specializations/cyber-security-business")
    back.setText("Back")

    f2.show()
    course_head.show()
    edx.show()
    l0.show()
    l1.show()
    l2.show()
    l3.show()
    l4.show()
    l5.show()
    coursera.show()
    l6.show()
    l7.show()
    l8.show()
    l9.show()
    l10.show()
    l11.show()
    back.show()

    def back1():
        f2.hide()
        course_head.hide()
        edx.hide()
        l0.hide()
        l1.hide()
        l2.hide()
        l3.hide()
        l4.hide()
        l5.hide()
        coursera.hide()
        l6.hide()
        l7.hide()
        l8.hide()
        l9.hide()
        l10.hide()
        l11.hide()
        back.hide()
        main.mainui(abc)

    back.clicked.connect(back1)

